name: Cory Tyler
favicon: null
layout_spectrum: 0.8419409615453333
typography_spectrum: 0.7328075536061078
title: CoryTyler
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f2f7'
    - '#c3cdd9'
    - '#575b66'
    - '#9ca2ae'
    - '#0f0e13'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
